version: 6.6.0
files:
  - url: Gitify-6.6.0.AppImage
    sha512: R2jaRXuberkQcV/kS1BlIiDfFmrYa9bIlJZsRHVtnNs41Rh67Y3uf+xJaCl4mPjRd49Vr5794sJSfv4lPiu/Nw==
    size: 110135032
    blockMapSize: 116492
  - url: gitify_6.6.0_amd64.deb
    sha512: B/NFaDCFQwJmI0Z/SIql0aqbJZiRfvsMw071ER3piubixWX+RrFdkLRDwLfo/iBmHGUt0wNAgwoQbCqdVGn6Nw==
    size: 75750556
  - url: gitify-6.6.0.x86_64.rpm
    sha512: mLbaDjyd47Ef2GgofA9ZxFEZ9PrgjtYQq7HxC58HWb0qYYxuPD6nhTVEg73ke8fl/Na8IGpXceUMvvBxWAB/mw==
    size: 75650321
path: Gitify-6.6.0.AppImage
sha512: R2jaRXuberkQcV/kS1BlIiDfFmrYa9bIlJZsRHVtnNs41Rh67Y3uf+xJaCl4mPjRd49Vr5794sJSfv4lPiu/Nw==
releaseDate: '2025-08-19T20:13:10.885Z'
